/**
 * Terminal graphics characters must ink the *whole* character cell: TUI art
 * (sparklines, braille plots, mosaic graphics, chafa-style output) is drawn as a
 * grid of sub-cells, so any mismatch between the glyph's ink box and the cell
 * shows up as gaps between rows - the "phantom line spacing" that makes such art
 * look broken.
 *
 * xterm.js rasterizes these ranges itself in the WebGL renderer (see
 * `scripts/patch-xterm-braille-grid.cjs`, which aligns the addon with the grid
 * below), but the DOM renderer has no custom glyph support at all and uses the
 * font instead:
 *
 *   - a regular monospace font inks only ~58% of the line height for braille
 *     (Maple Mono NF CN: 0.376em x 0.772em inside a 0.6em x 1.32em cell);
 *   - Symbols for Legacy Computing (sextants, mosaic graphics) are missing from
 *     essentially every font.
 *
 * NyaTerm therefore bundles a symbols-only font whose glyphs are drawn on the
 * cell grid (`public/fonts/nyaterm-symbols.ttf`, generated by
 * `scripts/generate-symbol-font.mjs`) and puts it first in the terminal font
 * stack. Its `unicode-range` covers only the two ranges below, so it never
 * affects the cell metrics that xterm.js measures from `W`, nor any other
 * character.
 */
export const TERMINAL_SYMBOL_FONT_FAMILY = "NyaTerm Symbols";

/**
 * Ranges shipped by `nyaterm-symbols.ttf`; keep in sync with the `unicode-range`
 * in `src/index.css` and with the generator.
 */
export const TERMINAL_SYMBOL_FONT_UNICODE_RANGE =
  "U+2800-28FF, U+1FB00-1FB3B, U+1FB68-1FB8B, U+1FBF0-1FBF9";

/**
 * Prefix a configured font stack with the bundled symbols font. It is listed
 * first because a font that already contains braille glyphs (e.g. Maple Mono
 * NF CN) would otherwise win the per-character fallback lookup.
 */
export function composeTerminalFontFamily(fontFamily: string): string {
  const symbols = `"${TERMINAL_SYMBOL_FONT_FAMILY}"`;
  const trimmed = fontFamily.trim();
  return trimmed ? `${symbols}, ${trimmed}` : `${symbols}, monospace`;
}

/**
 * Resolves once the symbols font finished loading. Browsers render fallback
 * glyphs for text that is already on screen while a webfont is still loading, so
 * callers should repaint the terminal after this resolves.
 */
export async function ensureTerminalSymbolFontReady(): Promise<boolean> {
  if (typeof document === "undefined" || !document.fonts) {
    return false;
  }

  try {
    const faces = await document.fonts.load(
      `16px "${TERMINAL_SYMBOL_FONT_FAMILY}"`,
      "\u2800\u28ff\u{1fb00}",
    );
    return faces.length > 0;
  } catch {
    return false;
  }
}
