[package]
name = "nyaterm-app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
gpui.workspace = true
gpui-kit.workspace = true
gpui_platform.workspace = true
nyaterm-core.workspace = true
nyaterm-desktop.workspace = true
nyaterm-ui.workspace = true
rust-embed.workspace = true

tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
nyaterm-core = { workspace = true, features = ["test-support"] }
usvg.workspace = true

[lib]
name = "nyaterm_app"
path = "src/lib.rs"

[[bin]]
name = "nyaterm"
path = "src/main.rs"


[features]
default = ["font-kit"]
font-kit = ["gpui_platform/font-kit"]

[build-dependencies]
embed-resource = "3.0"
